$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command
description: Phase 1 WGAN-GP Baseline Training
experiment_name: atml-brain-anomaly-baseline

# The code folder to upload to Azure (..)
code: ..

# Chain install scikit-learn and run 50 epochs
command: >-
  pip install scikit-learn && python ./scripts/train_baseline.py --epochs 50

environment: azureml:AzureML-ACPT-pytorch-1.11-py38-cuda11.3-gpu@latest
compute: azureml:gpu-cluster