"""
f-AnoGAN Discriminator (CNN Baseline)
---------------------------------------
Architecture: PatchGAN Discriminator

What this does:
  Looks at an image and decides: is this a real healthy brain scan,
  or a fake one generated by the Generator?

  It doesn't judge the whole image at once. Instead it uses a
  "PatchGAN" design — it slides a 70x70 window across the image
  and judges each patch independently. This catches local texture
  and structural inconsistencies much better than judging globally.

  Output: a grid of real/fake scores (one per patch), not a single number.

Based on: Schlegl et al., f-AnoGAN (2019)
         Isola et al., pix2pix (2017) — PatchGAN design
"""

import torch
import torch.nn as nn


class DiscriminatorBlock(nn.Module):
    """
    A single discriminator block: Conv → BatchNorm → LeakyReLU

    Same building block as the generator encoder, but used differently —
    here we're extracting features to make a real/fake judgment.
    """

    def __init__(self, in_channels, out_channels, stride=2, batch_norm=True):
        super().__init__()
        layers = [
            nn.Conv2d(in_channels, out_channels,
                      kernel_size=4, stride=stride, padding=1, bias=False)
        ]
        if batch_norm:
            layers.append(nn.BatchNorm2d(out_channels))
        layers.append(nn.LeakyReLU(0.2, inplace=True))
        self.block = nn.Sequential(*layers)

    def forward(self, x):
        return self.block(x)


class Discriminator(nn.Module):
    """
    PatchGAN Discriminator for f-AnoGAN.

    Input:  (batch, 1, 128, 128) — real or generated MRI slice
    Output: (batch, 1, 8, 8)    — grid of real/fake scores per patch

    Why output a grid and not a single number?
      A single number forces the discriminator to summarise the whole
      image in one judgment. A patch grid lets it say "this region
      looks fake but this other region looks real" — much more
      informative feedback for the generator to learn from.

    The effective receptive field of each output patch is 70x70 pixels
    in the original 128x128 image — covers enough context to judge
    local brain anatomy convincingly.
    """

    def __init__(self, in_channels=1, features=64):
        super().__init__()

        self.model = nn.Sequential(
            # No BatchNorm on first layer (standard practice)
            DiscriminatorBlock(in_channels, features,
                               stride=2, batch_norm=False),  # → (batch, 64,  64, 64)
            DiscriminatorBlock(features,     features * 2),  # → (batch, 128, 32, 32)
            DiscriminatorBlock(features * 2, features * 4),  # → (batch, 256, 16, 16)
            DiscriminatorBlock(features * 4, features * 8,
                               stride=1),                    # → (batch, 512, 15, 15)

            # Final layer: outputs real/fake score per patch
            # No activation — raw scores fed into loss function
            nn.Conv2d(features * 8, 1,
                      kernel_size=4, stride=1, padding=1)    # → (batch,   1,  14, 14)
        )

    def forward(self, x):
        return self.model(x)


# ── QUICK TEST ────────────────────────────────────────────────
if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Testing Discriminator on {device}...")

    model = Discriminator().to(device)

    # Simulate a batch of 4 MRI slices
    dummy_input = torch.randn(4, 1, 128, 128).to(device)
    output = model(dummy_input)

    print(f"Input shape  : {dummy_input.shape}")
    print(f"Output shape : {output.shape}")

    # Count parameters
    params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"Parameters   : {params:,}")
    print("✅ Discriminator test passed!")